use_frameworks!

platform :ios, '8.0'

target 'TuConfirmOrder_Example' do
  pod 'TuConfirmOrder', :path => '../'

  target 'TuConfirmOrder_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
