use_frameworks!

platform :ios, '8.0'
source 'https://github.com/wuzhantu/TuSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'TuConfirmOrder_Example' do
  pod 'TuConfirmOrder', :path => '../'

  target 'TuConfirmOrder_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
